# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.1
    working_directory: ~/node-hello
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-depedencies-
      - run: npm install
      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package.json"}}
      - run: npm start



